FROM ubuntu:22.04

RUN DEBIAN_FRONTEND=noninteractive apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libgmp-dev \
    nlohmann-json3-dev cmake libgrpc++-dev libprotobuf-dev uuid-dev pkg-config && \
    rm -fr /var/cache/apt/*

WORKDIR /usr/src/app

COPY ./src ./src
COPY ./test ./test
COPY ./tools ./tools
COPY Makefile .

RUN make -j && mv ./build/zkProver /usr/local/bin/zkProver

ENTRYPOINT []
