FROM ubuntu:22.04 as build

RUN DEBIAN_FRONTEND=noninteractive apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libgmp-dev \
    libbenchmark-dev nasm nlohmann-json3-dev libsecp256k1-dev libomp-dev \
    libpqxx-dev git libssl-dev cmake libgrpc++-dev libprotobuf-dev grpc-proto \
    libsodium-dev protobuf-compiler protobuf-compiler-grpc uuid-dev && \
    rm -fr /var/cache/apt/*

RUN DEBIAN_FRONTEND=noninteractive apt install -y libgmp-dev \
    nlohmann-json3-dev libsecp256k1-dev libomp-dev libpqxx-dev libssl-dev \
    libgrpc++-dev libprotobuf-dev grpc-proto libsodium-dev && \
    rm -fr /var/cache/apt/*

WORKDIR /usr/src/app
