FROM ubuntu:22.04 as executor

WORKDIR /app

RUN DEBIAN_FRONTEND=noninteractive apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y libgmp-dev \
    nlohmann-json3-dev libsecp256k1-dev libomp-dev libpqxx-dev libssl-dev \
    libgrpc++-dev libprotobuf-dev grpc-proto libsodium-dev && \
    rm -fr /var/cache/apt/*

ENTRYPOINT ["zkProver"]
CMD ["-c", "testvectors/config_runFile_BatchProof.json"]
